# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


path_to_data = "/home/turbo/d3i/local-modeler/data/data_lda.zip"
participant_id = "12345"

class TestTest():
  def setup_method(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get(f"http://localhost:3000/?participantId={participant_id}")
    # Wait for the confirm-button to be present
    WebDriverWait(self.driver, 30).until(
        EC.presence_of_element_located((By.ID, "confirm-button"))
    )
    self.driver.find_element(By.ID, "confirm-button").click()
    self.driver.find_element(By.ID, "input").send_keys(path_to_data)
    self.driver.find_element(By.CSS_SELECTOR, ".bg-primary > #confirm-button").click()
  

check = TestTest()
check.setup_method()
check.test_test()
check.teardown_method()
